# Verifies if a pull request has at least one label from a set of valid
# labels before it can be merged.

name: PR label checks

on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]

permissions:
  pull-requests: read

jobs:
  require-label:
    runs-on: ubuntu-latest
    steps:
      # Fail when none of the allowed labels are present
      - name: Validate required labels
        if: >-
          !(
            contains(github.event.pull_request.labels.*.name, '[maintainer]
          release') ||
            contains(github.event.pull_request.labels.*.name, '[scope] bug') ||
            contains(github.event.pull_request.labels.*.name, '[scope]
          documentation') ||
            contains(github.event.pull_request.labels.*.name, '[scope]
          enhancement') ||
            contains(github.event.pull_request.labels.*.name, '[scope]
          maintenance') ||
            contains(github.event.pull_request.labels.*.name, '[scope]
          significant') )
        run: |
          echo "::error::PR must have at least one of: [maintainer] release, [scope] bug, documentation, enhancement, maintenance, significant"
          exit 1
