name: Check code quality

on:
  # Trigger the workflow on push
  push:
    # Every branch
    branches: ['**']
    # But do not run this workflow on creating a new tag starting with
    # 'v', e.g. 'v1.0.3' (see publish-pypi.yml)
    tags-ignore: ['v*']
  # Trigger the workflow on pull request
  pull_request:
    branches: ['**']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent workflow, skipping runs queued between the run
# in-progress and latest queued. And cancel in-progress runs.
concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# Set the environment variables to be used in all jobs defined in this workflow
env:
  CI_BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  check-quality:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.0
        with:
          environments: default
          activate-environment: default
          run-install: true
          frozen: true
          cache: false
          post-cleanup: false

      - name: Install extra tools (Prettier)
        shell: bash
        run: |
          pixi run npm config set registry https://registry.npmjs.org/
          pixi run prettier-install

      # Check the validity of pyproject.toml
      - name: Check validity of pyproject.toml
        id: check_pyproject
        continue-on-error: true
        shell: bash
        run: pixi run pyproject-check

      # Check code linting with Ruff in the project root
      - name: Check code linting
        id: check_code_linting
        continue-on-error: true
        shell: bash
        run: pixi run py-lint-check

      - name: Suggestion to fix code linting issues (*.py files)
        if: steps.check_code_linting.outcome == 'failure'
        shell: bash
        run:
          echo "In project root run 'pixi run py-lint-fix' and commit changes"

      # Check code formatting with Ruff in the project root
      - name: Check code formatting
        id: check_code_formatting
        continue-on-error: true
        shell: bash
        run: pixi run py-format-check

      - name: Suggestion to fix code formatting issues (*.py files)
        if: steps.check_code_formatting.outcome == 'failure'
        shell: bash
        run:
          echo "In project root run 'pixi run py-format-fix' and commit changes"

      # Check formatting of Markdown, YAML, TOML, etc. files with Prettier in
      # the project root
      - name: Check formatting of Markdown, YAML, TOML, etc. files
        id: check_others_formatting
        continue-on-error: true
        shell: bash
        run: pixi run nonpy-format-check

      - name: Suggestion to fix non-code formatting issues (*.md, *.yml, etc.)
        if: steps.check_others_formatting.outcome == 'failure'
        shell: bash
        run:
          echo "In project root run 'pixi run nonpy-format-fix' and commit
          changes"

      - name: Force fail if any of the previous steps failed
        if: |
          steps.check_pyproject.outcome == 'failure' ||
          steps.check_code_linting.outcome == 'failure' ||
          steps.check_code_formatting.outcome == 'failure' ||
          steps.check_others_formatting.outcome == 'failure'
        run: exit 1
